arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan
    - shoulder_lift
    - elbow
    - wrist_flex
    - wrist_roll
    - grip_left
  gains:
    shoulder_pan:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_flex:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1